# Sample .travis.yml for R projects

language: r
bioc_required: true
bioc_packages: 
   - edgeR
warnings_are_errors: true
sudo: required
r_check_revdep: false

env:
 global:
   - CRAN: http://cran.rstudio.com
   - R_BUILD_ARGS="--no-build-vignettes --no-manual"
   - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
   - BIOC_USE_DEVEL="FALSE"
   - R_CHECK_TIME="TRUE"
   - R_CHECK_TESTS="TRUE"

notifications:
  email:
    on_success: change
    on_failure: change

  